### ISSUE TITLE
Failed to save changeset due to long reference layer name

### ISSUE THREAD

**Issue by susannaanas** [OpenHistoricalMap/iD#14]
"ChangesetTag 2312,imagery_used: v: is too long (maximum is 255 characters) ("Custom (http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/hel%3Aorto1964@EPSG%3A900913@png/{zoom}/{x}/{-y}.png);Custom (http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/hel%3Aorto1950@EPSG%3A900913@png/{zoom}/{x}/{-y}.png);Custom (http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/historical%3A1962_opaskartta@EPSG%3A900913@png/{zoom}/{x}/{-y}.png);Custom (http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/historical%3A1977_opaskartta@EPSG%3A900913@png/{zoom}/{x}/{-y}.png);Custom (http://geoserver.hel.fi/geoserver/gwc/service/tms/1.0.0/hel%3Aorto1976@EPSG%3A900913@png/{zoom}/{x}/{-y}.png)")"

**Comment by Abbe98** [comment]
This was patched over two years ago([commit](https://github.com/OpenHistoricalMap/iD/commit/38b821bdea3a72f2e5fb2a9adfc504bc6b82025c)).

This OHM iD instance is not the one on openhistoricalmap.org there for the bug is present there.
